list: $/akravets/survey/models/question/columns.yaml
modelClass: Akravets\Survey\Models\Question
title: Questions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'akravets/survey/questions/update/:id'
